# Generated by Django 3.2.6 on 2021-08-20 03:46

from django.db import migrations

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

import random
from datetime import datetime as DT
from datetime import timedelta

def get_random_date(start, end):
    delta = end - start
    return start + timedelta(random.randint(0, delta.days))

def beginning(apps, schema_editor):

    # Суперпользователь 
    user = User.objects.create_superuser(username='root',
    email='best.price.test@mail.ru',
    password='SsNn5678+-@')
    print("Суперпользователь создан")
    
    # Группа менеджеров
    managers = Group.objects.get_or_create(name = 'Managers')
    managers = Group.objects.get(name='Managers')
    print("Группа менеджеров создана")
    
    # Пользователь с ролью менеджера id
    user = User.objects.create_user(username='manager', password='Ss0066+-')
    managers.user_set.add(user)
    print("Менеджер добавлен в группу менеджеров")

    # Диапазон дат
    start_dt = DT.strptime('2022-01-01', '%Y-%m-%d')
    end_dt = DT.strptime('2022-08-31', '%Y-%m-%d')

    Prices = apps.get_model("bestprice", "Prices")
    
    for i in range(10000):
        prices = Prices()
        prices.datep = get_random_date(start_dt, end_dt)
        prices.store = 'Магазин ' + str(random.randint(1,10))
        prices.product = 'Товар ' + str(random.randint(1,1000))
        prices.cost = random.randint(100,5000)
        prices.details = ''
        prices.save()
        print(i)
    

class Migration(migrations.Migration):

    dependencies = [
        ('bestprice', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(beginning),
    ]
